name: food_delivery_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  collection: ^1.18.0
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#FFF"
    theme_color: white

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SchibstedGrotesk
      fonts:
        - asset: assets/fonts/SchibstedGrotesk-VariableFont_wght.ttf
